version: '3.8'
services:
  payment-service:
    build: ./ps-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: paymentdb
      POSTGRES_USER: payment
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
