version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: payment
      DB_PASSWORD: secret
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: payment
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: paymentdb
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"